# Generated by Django 5.2.5 on 2025-08-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_details', to='users.profile')),
            ],
        ),
    ]
