# Generated by Django 5.2.6 on 2025-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
