# Generated by Django 5.2.6 on 2025-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_restaurantprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
