# Generated by Django 5.2.5 on 2025-08-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_capacity_remove_profile_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdetails',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='restaurantdetails',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='restaurantdetails',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='restaurantdetails',
            name='tax_id',
        ),
    ]
