# Generated by Django 5.2.5 on 2025-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_restaurantdetails_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='restaurantdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
