# Generated by Django 5.2.5 on 2025-08-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='restaurantdetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
