# Generated by Django 5.2.5 on 2025-08-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdetails',
            old_name='company_name',
            new_name='name',
        ),
    ]
