# Generated by Django 5.2.5 on 2025-08-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_company_name_restaurantdetails_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantdetails',
            options={'verbose_name': 'Restaurant Detail', 'verbose_name_plural': 'Restaurant Details'},
        ),
    ]
