# Generated by Django 5.2.6 on 2025-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='theme_choice',
            field=models.CharField(choices=[('synthwave', 'Synthwave'), ('elegant', 'Elegant'), ('minimal', 'Minimal')], default='synthwave', help_text='Select the theme for your restaurant page.', max_length=32),
        ),
    ]
