# Generated by Django 5.2.6 on 2025-09-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_restaurantprofile_theme_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='theme_choice',
            field=models.CharField(choices=[('synthwave', 'Synthwave'), ('elegant', 'Elegant'), ('minimal', 'Minimal'), ('default', 'Default')], default='synthwave', help_text='Select the theme for your restaurant page.', max_length=32),
        ),
    ]
