# Generated by Django 5.2.6 on 2025-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_restaurantprofile_theme_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='about_description',
            field=models.TextField(blank=True, help_text='Description for the About Us section.', null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='about_headline',
            field=models.CharField(blank=True, help_text='Headline for the About Us section.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='about_highlight',
            field=models.CharField(blank=True, help_text='Highlighted quote or fact for the About Us section.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for the About Us section.', null=True, upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Short description for the hero section.', null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Headline for the hero section on the landing page.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the hero section.', null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='theme_choice',
            field=models.CharField(choices=[('synthwave', 'Synthwave'), ('elegant', 'Elegant'), ('minimal', 'Minimal'), ('default', 'Default')], default='default', help_text='Select the theme for your restaurant page.', max_length=32),
        ),
    ]
