# Generated by Django 5.2.6 on 2025-09-23 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_restaurantprofile_about_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image for the About Us section.', max_length=255, null=True, verbose_name='About image'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Background image for the hero section.', max_length=255, null=True, verbose_name='Hero image'),
        ),
    ]
