# Generated by Django 5.2.5 on 2025-09-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_menu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
