# Generated by Django 5.2.5 on 2025-09-02 19:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_menuitem_menu_delete_menu_delete_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Restaurant logo'),
        ),
    ]
