# Generated by Django 5.2.6 on 2025-09-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customerprofile'),
        ('users', '0012_create_user_groups'),
    ]

    operations = [
    ]
