# Generated by Django 5.2.6 on 2025-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Customer's phone number for this order", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=40, help_text='Maximum number of guests the restaurant can accommodate at once'),
        ),
    ]
