# Generated by Django 5.2.6 on 2025-09-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_order_phone_number_restaurantprofile_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
