# Generated by Django 5.2.6 on 2025-10-02 19:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_openinghour_is_closed_alter_openinghour_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the document')),
                ('category', models.CharField(choices=[('requirements', 'Requirements & Analysis'), ('design', 'Design & Architecture'), ('implementation', 'Implementation'), ('testing', 'Testing & Quality Assurance'), ('user_guide', 'User Guide & Documentation'), ('presentation', 'Presentations'), ('other', 'Other')], default='other', max_length=50)),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF Document'), ('google_doc', 'Google Doc'), ('google_slides', 'Google Slides'), ('google_sheets', 'Google Sheets'), ('image', 'Image/Screenshot'), ('other', 'Other')], default='pdf', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a PDF or image file', max_length=255, null=True, verbose_name='document')),
                ('google_doc_url', models.URLField(blank=True, help_text='Full URL to Google Doc, Slides, or Sheets', null=True)),
                ('embed_url', models.URLField(blank=True, help_text='Embed URL (auto-generated from Google Doc URL)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_published', models.BooleanField(default=True, help_text='Show on documentation page')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='about_description',
            field=models.TextField(blank=True, help_text='Write a few sentences describing your restaurant’s story, atmosphere, cuisine, or what makes it special.Keep it engaging and easy to read.', null=True, verbose_name='About Your Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='about_headline',
            field=models.CharField(blank=True, help_text='A short, punchy headline that introduces your restaurant in the About section.Make it inviting and memorable,it’s the first thing guests will read!', max_length=120, null=True, verbose_name='Your About Section Headline'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='about_highlight',
            field=models.CharField(blank=True, help_text='signature dishes, awards, unique experiences, or anything that sets you apart.', max_length=120, null=True, verbose_name='Share your restaurant’s standout features'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Write a brief description that captures the essence of your restaurant.', null=True, verbose_name='Short description for the top of your page'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Headline for the main section on the landing page.', max_length=120, null=True, verbose_name='Main headline'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Background image for the hero section.', max_length=255, null=True, verbose_name='Background image for the top of your page'),
        ),
    ]
