# Generated by Django 5.2.6 on 2025-10-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_document_alter_restaurantprofile_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, help_text="Restaurant owner's response", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
