# Generated by Django 5.2.5 on 2025-08-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder_app_create_page', '0002_template_author_template_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('button', 'Button'), ('menu_item', 'Menu Item')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='menu_photos/')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='page_builder_app_create_page.webpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
