# Generated by Django 5.2.5 on 2025-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder_app_create_page', '0003_pageelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageelement',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='pageelement',
            name='item_photo',
        ),
        migrations.RemoveField(
            model_name='pageelement',
            name='item_price',
        ),
        migrations.AddField(
            model_name='webpage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('button', 'Button')], max_length=50),
        ),
    ]
