# Generated by Django 5.2.6 on 2025-09-13 20:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional image for the menu item.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
