# Generated by Django 5.2.6 on 2025-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_updated_at_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('appetizers', 'Appetizers'), ('sides', 'Sides'), ('specials', 'Specials'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('kids', "Kids' Menu"), ('hot_drinks', 'Hot Drinks')], max_length=20),
        ),
    ]
