# Generated by Django 5.2.5 on 2025-09-07 15:09

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_owner_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['section', 'name']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(help_text='List main ingredients', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], max_length=20),
        ),
    ]
