# Generated by Django 5.2.6 on 2025-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menuitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='popular_items',
            field=models.BooleanField(default=False, help_text='Mark this item as a popular dish'),
        ),
    ]
