# Generated by Django 5.2.5 on 2025-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(default='Fresh ingredients', help_text='List main ingredients', max_length=200),
        ),
    ]
