# Generated by Django 5.2.6 on 2025-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_popular_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['section', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this item within its section'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('main', 'Main Courses'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('appetizers', 'Appetizers'), ('sides', 'Sides'), ('specials', 'Specials'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('kids', "Kids' Menu"), ('hot_drinks', 'Hot Drinks')], max_length=20),
        ),
    ]
