# Generated by Django 5.2.6 on 2025-09-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_address', models.CharField(help_text='The full, formatted address returned by Google.', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('restaurant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.restaurantprofile')),
            ],
        ),
    ]
