# Generated by Django 5.2.6 on 2025-09-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_customeraddress'),
        ('users', '0011_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customerprofile'),
        ),
    ]
